---
- name : IOS_config module example
  hosts: "ios-routers"
  gather_facts: false
  connection: local


  tasks:
#    - name: configure top level configuration
#      ios_config:
#        commands: hostname {{ inventory_hostname }}

    - name: configure interface settings
      ios_config:
        commands:
          - description test interface
          - ip address 172.31.1.3 255.255.255.0
        parents: interface lo10
        provider: "{{ cli }}"
